# Generated by Django 4.2.30 on 2026-06-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10, verbose_name='性别')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('id_number', models.CharField(blank=True, default='', max_length=18, verbose_name='身份证号')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='电话')),
                ('address', models.TextField(blank=True, default='', verbose_name='地址')),
                ('medical_record_number', models.CharField(max_length=50, unique=True, verbose_name='病历号')),
                ('allergies', models.TextField(blank=True, default='', verbose_name='过敏史')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '患者',
                'verbose_name_plural': '患者',
                'ordering': ['-created_at'],
            },
        ),
    ]
