# Generated by Django 4.2.30 on 2026-06-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('model_type', models.CharField(choices=[('detector', '检测模型'), ('classifier', '分类模型')], max_length=20, verbose_name='模型类型')),
                ('version', models.CharField(max_length=50, verbose_name='版本')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'ML模型记录',
                'verbose_name_plural': 'ML模型记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
