# Generated by Django 6.0.6 on 2026-06-21 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='食材名称')),
                ('category', models.CharField(choices=[('vegetable', '蔬菜'), ('fruit', '水果'), ('meat', '肉类'), ('seafood', '海鲜'), ('dairy', '乳制品'), ('grain', '谷物'), ('seasoning', '调料'), ('other', '其他')], default='other', max_length=20, verbose_name='分类')),
                ('unit', models.CharField(default='克', max_length=20, verbose_name='单位')),
                ('calories', models.FloatField(default=0, verbose_name='热量(kcal)')),
                ('protein', models.FloatField(default=0, verbose_name='蛋白质(g)')),
                ('fat', models.FloatField(default=0, verbose_name='脂肪(g)')),
                ('carbs', models.FloatField(default=0, verbose_name='碳水化合物(g)')),
                ('fiber', models.FloatField(default=0, verbose_name='膳食纤维(g)')),
                ('vitamin_c', models.FloatField(default=0, verbose_name='维生素C(mg)')),
                ('calcium', models.FloatField(default=0, verbose_name='钙(mg)')),
                ('iron', models.FloatField(default=0, verbose_name='铁(mg)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ingredients/', verbose_name='图片')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('price_per_unit', models.FloatField(default=0, verbose_name='单价(元)')),
            ],
            options={
                'verbose_name': '食材',
                'verbose_name_plural': '食材',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supermarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='超市名称')),
                ('address', models.CharField(max_length=500, verbose_name='地址')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='纬度')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否营业')),
                ('delivery_radius', models.FloatField(default=5, verbose_name='配送范围(公里)')),
            ],
            options={
                'verbose_name': '超市',
                'verbose_name_plural': '超市',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NutritionGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_calories', models.FloatField(default=2000, verbose_name='每日热量目标(kcal)')),
                ('daily_protein', models.FloatField(default=60, verbose_name='每日蛋白质目标(g)')),
                ('daily_fat', models.FloatField(default=65, verbose_name='每日脂肪目标(g)')),
                ('daily_carbs', models.FloatField(default=300, verbose_name='每日碳水目标(g)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_goal', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '营养目标',
                'verbose_name_plural': '营养目标',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='菜谱名称')),
                ('description', models.TextField(blank=True, verbose_name='简介')),
                ('cuisine', models.CharField(choices=[('sichuan', '川菜'), ('cantonese', '粤菜'), ('shandong', '鲁菜'), ('jiangsu', '苏菜'), ('fujian', '闽菜'), ('zhejiang', '浙菜'), ('hunan', '湘菜'), ('anhui', '徽菜'), ('chinese_home', '家常菜'), ('western', '西餐'), ('japanese', '日料'), ('korean', '韩餐'), ('other', '其他')], default='chinese_home', max_length=20, verbose_name='菜系')),
                ('difficulty', models.CharField(choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难')], default='medium', max_length=20, verbose_name='难度')),
                ('cook_time', models.IntegerField(default=30, verbose_name='烹饪时间(分钟)')),
                ('servings', models.IntegerField(default=2, verbose_name='份量(人份)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/', verbose_name='菜谱图片')),
                ('steps', models.TextField(verbose_name='烹饪步骤')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '菜谱',
                'verbose_name_plural': '菜谱',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('meal_type', models.CharField(choices=[('breakfast', '早餐'), ('lunch', '午餐'), ('dinner', '晚餐'), ('snack', '加餐')], max_length=20, verbose_name='餐次')),
                ('servings', models.IntegerField(default=1, verbose_name='份量')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to='recipes.recipe', verbose_name='菜谱')),
            ],
            options={
                'verbose_name': '饮食计划',
                'verbose_name_plural': '饮食计划',
                'ordering': ['date', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=100, verbose_name='用量')),
                ('unit', models.CharField(default='克', max_length=20, verbose_name='单位')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipes.ingredient', verbose_name='食材')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipes.recipe', verbose_name='菜谱')),
            ],
            options={
                'verbose_name': '菜谱食材',
                'verbose_name_plural': '菜谱食材',
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipes.RecipeIngredient', to='recipes.ingredient'),
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='清单名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_sent', models.BooleanField(default=False, verbose_name='是否已发送到超市')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('supermarket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.supermarket', verbose_name='超市')),
            ],
            options={
                'verbose_name': '购物清单',
                'verbose_name_plural': '购物清单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0, verbose_name='数量')),
                ('unit', models.CharField(default='克', max_length=20, verbose_name='单位')),
                ('is_purchased', models.BooleanField(default=False, verbose_name='是否已购买')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_items', to='recipes.ingredient', verbose_name='食材')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='recipes.shoppinglist', verbose_name='购物清单')),
            ],
            options={
                'verbose_name': '购物清单项',
                'verbose_name_plural': '购物清单项',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='recipes.recipe', verbose_name='菜谱')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'recipe')},
            },
        ),
    ]
