# Generated by Django 4.2.30 on 2026-06-14 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_uid', models.CharField(max_length=100, unique=True, verbose_name='检查UID')),
                ('study_date', models.DateField(blank=True, null=True, verbose_name='检查日期')),
                ('study_description', models.CharField(blank=True, default='', max_length=255, verbose_name='检查描述')),
                ('modality', models.CharField(choices=[('CT', 'CT'), ('MRI', 'MRI'), ('X-Ray', 'X-Ray')], default='CT', max_length=10, verbose_name='检查类型')),
                ('body_part', models.CharField(choices=[('chest', '胸部'), ('abdomen', '腹部'), ('head', '头部')], default='chest', max_length=20, verbose_name='检查部位')),
                ('status', models.CharField(choices=[('pending', '待分析'), ('analyzing', '分析中'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('dicom_file', models.FileField(blank=True, null=True, upload_to='dicom/', verbose_name='DICOM文件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='patients.patient', verbose_name='患者')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_studies', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '影像检查',
                'verbose_name_plural': '影像检查',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_data', models.JSONField(default=dict, verbose_name='标注数据')),
                ('annotation_type', models.CharField(choices=[('annotation', '标注'), ('measurement', '测量')], default='annotation', max_length=20, verbose_name='标注类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('annotator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL, verbose_name='标注者')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='studies.study', verbose_name='影像检查')),
            ],
            options={
                'verbose_name': '影像标注',
                'verbose_name_plural': '影像标注',
                'ordering': ['-created_at'],
            },
        ),
    ]
