# Generated by Django 4.2.30 on 2026-06-14 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nodule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(verbose_name='X坐标')),
                ('y', models.FloatField(verbose_name='Y坐标')),
                ('width', models.FloatField(verbose_name='宽度')),
                ('height', models.FloatField(verbose_name='高度')),
                ('diameter_mm', models.FloatField(blank=True, null=True, verbose_name='直径(mm)')),
                ('volume_mm3', models.FloatField(blank=True, null=True, verbose_name='体积(mm³)')),
                ('nodule_type', models.CharField(choices=[('solid', '实性结节'), ('part_solid', '部分实性结节'), ('ground_glass', '磨玻璃结节')], default='solid', max_length=20, verbose_name='结节类型')),
                ('malignancy_score', models.IntegerField(default=0, verbose_name='恶性评分')),
                ('malignancy_level', models.CharField(choices=[('benign', '良性'), ('likely_benign', '可能良性'), ('uncertain', '不确定'), ('likely_malignant', '可能恶性'), ('malignant', '恶性')], default='benign', max_length=20, verbose_name='恶性等级')),
                ('density', models.FloatField(blank=True, null=True, verbose_name='密度')),
                ('margin', models.CharField(choices=[('smooth', 'smooth'), ('irregular', 'irregular'), ('spiculated', 'spiculated')], default='smooth', max_length=20, verbose_name='边缘特征')),
                ('features', models.JSONField(default=dict, verbose_name='特征数据')),
                ('detected_by', models.CharField(choices=[('AI', 'AI'), ('manual', '人工')], default='AI', max_length=10, verbose_name='检测方式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('detector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detected_nodules', to=settings.AUTH_USER_MODEL, verbose_name='检测者')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodules', to='studies.study', verbose_name='影像检查')),
            ],
            options={
                'verbose_name': '结节',
                'verbose_name_plural': '结节',
                'ordering': ['-created_at'],
            },
        ),
    ]
