# Generated by Django 4.2.30 on 2026-06-14 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='会诊标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='会诊描述')),
                ('status', models.CharField(choices=[('pending', '待会诊'), ('in_progress', '会诊中'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('result', models.TextField(blank=True, default='', verbose_name='会诊结论')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('experts', models.ManyToManyField(related_name='expert_consultations', to=settings.AUTH_USER_MODEL, verbose_name='会诊专家')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_consultations', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='studies.study', verbose_name='影像检查')),
            ],
            options={
                'verbose_name': '专家会诊',
                'verbose_name_plural': '专家会诊',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('attachments', models.JSONField(default=list, verbose_name='附件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_comments', to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='consultations.consultation', verbose_name='会诊')),
            ],
            options={
                'verbose_name': '会诊评论',
                'verbose_name_plural': '会诊评论',
                'ordering': ['created_at'],
            },
        ),
    ]
