version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: smart-irrigation-backend
    restart: unless-stopped
    ports:
      - "9000:8080"
    volumes:
      - ./backend/data:/app/data
    environment:
      - GIN_MODE=release

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: smart-irrigation-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db-data:
