server:
  port: 9003

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:sqlite:data/order.db
    driver-class-name: org.sqlite.JDBC
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
