# Generated by Django 4.2.30 on 2026-06-14 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('initial', '初诊报告'), ('follow_up', '复诊报告'), ('consultation', '会诊报告')], default='initial', max_length=20, verbose_name='报告类型')),
                ('findings', models.TextField(blank=True, default='', verbose_name='检查所见')),
                ('conclusion', models.TextField(blank=True, default='', verbose_name='诊断结论')),
                ('recommendation', models.TextField(blank=True, default='', verbose_name='建议')),
                ('nodules_summary', models.JSONField(default=dict, verbose_name='结节摘要')),
                ('is_signed', models.BooleanField(default=False, verbose_name='是否签发')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='签发时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_reports', to=settings.AUTH_USER_MODEL, verbose_name='报告作者')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='patients.patient', verbose_name='患者')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_reports', to=settings.AUTH_USER_MODEL, verbose_name='签发人')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='studies.study', verbose_name='影像检查')),
            ],
            options={
                'verbose_name': '诊断报告',
                'verbose_name_plural': '诊断报告',
                'ordering': ['-created_at'],
            },
        ),
    ]
